import axios from "axios";

const FIREBASE_URL = "https://expense-tracker-app-5155d-default-rtdb.firebaseio.com";

const storeExpense = async (expenseData) => {
    const response = await axios.post(FIREBASE_URL + "/expenses.json", expenseData);
    const expenseId = response.data.name; // the "name" property holds the id generated by firebase
    return expenseId;
};

const fetchExpenses = async () => {
    const response = await axios.get(FIREBASE_URL + "/expenses.json");
    const expenses = [];

    for (const key in response.data) {
        const expenseObj = {
            id: key,
            amount: response.data[key].amount,
            date: new Date(response.data[key].date),
            description: response.data[key].description
        };
        expenses.push(expenseObj);
    }

    return expenses;
};

const updateExpense = async (id, expenseData) => {
    // here we are simply returning the promise object itself (not its result).
    return await axios.put(FIREBASE_URL + `/expenses/${id}.json`, expenseData);
};

const deleteExpense = async (id) => {
    return await axios.delete(FIREBASE_URL + `/expenses/${id}.json`);
};

export { storeExpense, fetchExpenses, updateExpense, deleteExpense };

// axios gives us a "data" (i.e response.data) property on the response object which contains the data that was sent back by the server.
